# Generated by Django 5.1.2 on 2024-10-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('ic', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('driver', 'Driver')], max_length=10)),
            ],
        ),
    ]
