# Generated by Django 5.1.2 on 2024-11-07 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
