# Generated by Django 5.1.2 on 2024-10-28 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        ('person', '0001_initial'),
        ('products', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('customer_ticket_no', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_qty', models.IntegerField(default=0)),
                ('ticket_no', models.CharField(max_length=100)),
                ('do', models.CharField(max_length=100)),
                ('weight_in', models.IntegerField(default=0)),
                ('weight_out', models.IntegerField(default=0)),
                ('factory_nett', models.IntegerField(default=0)),
                ('deduction', models.IntegerField(default=0)),
                ('bucket', models.FloatField(default=0.0)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(limit_choices_to={'type': 'customer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='person.person')),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='destinations.destination')),
                ('driver', models.ForeignKey(limit_choices_to={'type': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to='person.person')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('supplier', models.ForeignKey(limit_choices_to={'type': 'supplier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier', to='person.person')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicle')),
            ],
        ),
    ]
