# Generated by Django 5.1.2 on 2024-10-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='nett',
            field=models.IntegerField(default=0),
        ),
    ]
