# Generated by Django 5.1.2 on 2026-07-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('ton', 'Ton')], default='kg', max_length=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='deduction',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='factory_nett',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='nett',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='supplier_qty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='weight_in',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='weight_out',
            field=models.FloatField(default=0),
        ),
    ]
