# Generated by Django 5.1.2 on 2026-07-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0002_inventory_unit_alter_inventory_deduction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastSelectedUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('ton', 'Ton')], default='kg', max_length=10)),
            ],
        ),
    ]
