# Generated by Django 5.1.2 on 2024-11-05 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
        ('inventories', '0003_alter_inventory_nett'),
        ('person', '0001_initial'),
        ('products', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='bucket',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='deduction',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='destinations.destination'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to='person.person'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='factory_nett',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='supplier',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'supplier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier', to='person.person'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicle'),
        ),
    ]
