# Generated by Django 5.1.2 on 2024-11-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0005_remove_inventory_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='ticket_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
